server:
  port: 8810

spring:
  application:
    name: security-client

  thymeleaf:
    suffix: .html
    cache: false
    encoding: UTF-8
    mode: HTML5
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/spring_cloud_auth?
    useSSL=false&useUnicode=true&
    characterEncoding=UTF-8&
    allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true