server:
  port: 8769

eureka:
  client:
    service-url:
        defaultZone:
          http://localhost:8761/eureka/
spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        #远程仓库
        git:
          uri: https://github.com/wuran-github/config-server.git
          search-paths: configs
          #username: wuran-github
          #password:
          default-label: master

        # 本地文件夹
        #native:
        #  search-locations: classpath:/shared
      label: master
  profiles:
    #远程需要配置为remote
    active: remote
    #本地则是native
    #active: native


